### ISSUE TITLE
Could this be made to work on mobile.twitter.com?

### ISSUE THREAD

**Issue by akotro** [sindresorhus/refined-twitter#145] opened 2018-09-20 06:32 UTC
Mobile twitter is much better than desktop twitter imo, could this be made to work on that as well?

**Comment by sindresorhus** [comment] 2018-09-20 06:35
Duplicate of #115

**Comment by sindresorhus** [comment] 2018-09-20 06:35
tl;dr; I tried it once before and it was not maintainable.

**Closed as completed by sindresorhus** 2018-09-20 06:35 UTC
