### ISSUE TITLE
Render inline code with monospace font

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/refined-twitter#68] opened 2018-02-19 19:36 UTC
https://twitter.com/left_pad/status/940723982638157829
![image](https://user-images.githubusercontent.com/10532611/36394446-293a9a62-1569-11e8-9821-209e7fee1fb1.png)

should render like `class A extends HTMLElement {}`

**Comment by sindresorhus** [comment] 2018-02-19 19:54
Duplicate of #9

**Closed as completed by sindresorhus** 2018-02-19 19:54 UTC
