### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by OleksandrBilenko** [sindresorhus/refined-twitter#128] opened 2018-07-19 19:48 UTC
Hi! Good project, hope you will continue improving it. Please add settings page to let users activate and deactivate extension features. List of checkboxes with short description will be enough. Thank you!

**Comment by sindresorhus** [comment] 2018-07-19 19:49
Duplicate of #38

**Comment by sindresorhus** [comment] 2018-07-19 19:49
Out of curiosity, what features would you have turned off if it was possible and why?

**Closed as completed by sindresorhus** 2018-07-19 19:49 UTC

**Comment by OleksandrBilenko** [comment] 2018-07-19 19:55
I like to see my profile details on the main page. There are useful links and counters on this panel which I use frequently
